Repository betabites/discord-against-humanity, pull requests merged in 2021-07, with the labels that each got.

#1 Added all minimum features
  .gitignore
  .idea/.gitignore
  .idea/discord-against-humanity.iml
  .idea/jsLibraryMappings.xml
  .idea/modules.xml
  .idea/vcs.xml
  README.md
  index.js
  package.json
  test.html
Labels: enhancement

#3 Updated installation & usage instructions.
  README.md
  pack.json
Labels: documentation

#7 Fixes to some minor & major bugs
  index.js
Labels: bug
